- README.md
> fix:readme spelling error

- lib/client.js
- lib/leader.js
- lib/utils.js
> refact: improve utils.delegateEvents()

- lib/index.js
- package.json
> fix: no more need harmony-reflect on node >= 6

- lib/server.js
- package.json
- test/egg.test.js
- test/index.test.js
> Fix block remote ip

- lib/client.js
> chore: better notice

- lib/client.js
- lib/follower.js
- lib/leader.js
- test/index.test.js
- Leader 在同一时间订阅多次的问题
- 心跳超时的检查 bug
> fix: fix leader subscribe issue & heartbeat timeout issue

- README.md
- index.js
- lib/api_client.js
- lib/index.js
- package.json
- test/client.test.js
- test/index.test.js
> feat: add APIClientBase to help you create your api client

- lib/api_client.js
> fix: don't auto ready when initMethod exists

- lib/client.js
- lib/leader.js
- lib/utils.js
- test/ready.test.js
- test/utils.test.js
> fix: event delegate & leader ready bug

- lib/leader.js
- test/client.test.js
> fix: make sure that subscribe listener is triggered asynchronized

- lib/index.js
- package.json
- test/index.test.js
> feat: make clustClient method writable to support mock or spy

- lib/index.js
- test/index.test.js
> fix: fix symbol property error

- .gitignore
- lib/server.js
closes https://github.com/eggjs/egg/issues/432
> fix: make sure follower test socket end

- appveyor.yml
- lib/api_client.js
- lib/client.js
- lib/server.js
- test/cluster.test.js
- test/supports/cluster_server.js
make sure handle is not shared on cluster module
> fix: set exclusive to true on listen

- lib/server.js
- test/close.test.js
> fix: only close server when server exists

- .travis.yml
- appveyor.yml
- lib/client.js
- lib/index.js
- lib/leader.js
- lib/server.js
- lib/utils.js
- package.json
- test/async.test.js
- test/client.test.js
- test/close.test.js
- test/cluster.test.js
- test/connection.test.js
- test/event.test.js
- test/index.test.js
- test/register_error.test.js
- test/server.test.js
- test/supports/async_api_client.js
- test/supports/async_data_client.js
- test/supports/cluster_server.js
- test/utils.test.js
> [BREAKING] feat: migrating from generators to async/await

- lib/follower.js
- lib/leader.js
- test/client.test.js
> feat: response with whole error object instead of only stack, message

- lib/client.js
- lib/index.js
- lib/server.js
- package.json
- test/index.test.js
- test/supports/cluster_server.js
> fix: adjust socket connect timeout

- .travis.yml
- appveyor.yml
- lib/client.js
- package.json
- test/index.test.js
> fix: remove follower connect timeout warning

- lib/index.js
> feat: connectTimeout support env, default 10s

- lib/index.js
- lib/leader.js
不影响
增加是否检查心跳参数isCheckHeartbeat，ref: https://github.com/eggjs/egg/issues/5057
> feat:add options isCheckHeartbeat of whether check heartbeat

- .github/workflows/nodejs.yml
- lib/follower.js
- package.json
- test/subscribe.test.js
> fix: should not emit timeout when has cache

- .github/workflows/nodejs.yml
- .github/workflows/release.yml
- lib/index.js
- package.json
> fix: Auto release on action

- lib/server.js
- lib/wrapper/base.js
- lib/wrapper/cluster.js
> fix: add more debug log

- README.md
- lib/server.js
- lib/wrapper/base.js
- test/server.test.js
> feat: throw error when create server port is missing
